name: Xcodegen

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.1
        with: 
          spec: Dynavity/project.yml

